Schema.voices.Add("CitizenMale", "BE CAREFUL", "Be careful now.", "vo/canals/boxcar_becareful.wav")
Schema.voices.Add("CitizenMale", "CAN'T AFFORD", "We really can't afford to get noticed.", "vo/canals/boxcar_becareful_b.wav")
Schema.voices.Add("CitizenMale", "GET GOING", "Get going now.", "vo/canals/boxcar_go_nag01.wav")
Schema.voices.Add("CitizenMale", "GET GOING2", "Better get going.", "vo/canals/boxcar_go_nag02.wav")
Schema.voices.Add("CitizenMale", "GET OUTTA HERE", "Get outta here.", "vo/canals/boxcar_go_nag03.wav")
Schema.voices.Add("CitizenMale", "HIT THE ROAD JACK", "Hit the road, Jack.", "vo/canals/boxcar_go_nag04.wav")
Schema.voices.Add("CitizenMale", "HELL HELP YOU", "He'll help you if you let him.", "vo/canals/boxcar_lethimhelp.wav")
Schema.voices.Add("CitizenMale", "SIRENS ARE FOR YOU", "Guess those sirens are for you, huh?", "vo/canals/boxcar_sirens.wav")
Schema.voices.Add("CitizenMale", "YOU FOUND US", "Good thing you found us.", "vo/canals/boxcar_sirens_b.wav")
Schema.voices.Add("CitizenMale", "ILL SHOW YOU", "Come on in, I'll show you what you're up against.", "vo/canals/gunboat_comein.wav")
Schema.voices.Add("CitizenMale", "FINISHING UP NOW", "I think he's just finishing up now.", "vo/canals/gunboat_finishingup.wav")
Schema.voices.Add("CitizenMale", "GET IN HERE", "Come on, get in here.", "vo/canals/gunboat_getin.wav")
Schema.voices.Add("CitizenMale", "GO ON OUT", "Go on out.", "vo/canals/gunboat_goonout.wav")
Schema.voices.Add("CitizenMale", "TAKE A LOOK AT THIS", "Here, take a look at this.", "vo/canals/gunboat_herelook.wav")
Schema.voices.Add("CitizenMale", "POOR BASTARD", "Poor bastard doesn't stand a chance.", "vo/canals/matt_beglad_b.wav")
Schema.voices.Add("CitizenMale", "CLOSE CALL", "That was a close call. Thanks for your help.", "vo/canals/matt_closecall.wav")
Schema.voices.Add("CitizenMale", "BEFORE THEY SWEEP", "You better get going before they sweep through here.", "vo/canals/matt_flood_b.wav")
Schema.voices.Add("CitizenMale", "GET IN HERE2", "Get in here, hurry!", "vo/canals/matt_getin.wav")
Schema.voices.Add("CitizenMale", "GET GOING NOW", "You better get going now.", "vo/canals/matt_go_nag01.wav")
Schema.voices.Add("CitizenMale", "GET GOING3", "Get going.", "vo/canals/matt_go_nag04.wav")
Schema.voices.Add("CitizenMale", "GO ON2", "You go on.", "vo/canals/matt_go_nag05.wav")
Schema.voices.Add("CitizenMale", "GOOD LUCK OUT THERE", "Good luck out there!", "vo/canals/matt_goodluck.wav")
Schema.voices.Add("CitizenMale", "TOO LATE", "Oh shit! Too late!", "vo/canals/matt_toolate.wav")
Schema.voices.Add("CitizenMale", "BAD TIME", "You got here at a bad time.", "vo/canals/shanty_badtime.wav")
Schema.voices.Add("CitizenMale", "GET OUTTA HERE2", "Get outta here!", "vo/canals/shanty_go_nag01.wav")
Schema.voices.Add("CitizenMale", "GO ON", "Go on!", "vo/canals/shanty_go_nag02.wav")
Schema.voices.Add("CitizenMale", "GET GOING4", "Get going!", "vo/canals/shanty_go_nag03.wav")
Schema.voices.Add("CitizenMale", "HEY", "Hey!", "vo/canals/shanty_hey.wav")
Schema.voices.Add("CitizenMale", "INCOMING", "Incoming!", "vo/canals/male01/stn6_incoming.wav")
Schema.voices.Add("CitizenMale", "THEYRE SHELLING US", "They're shelling us!", "vo/canals/male01/stn6_shellingus.wav")
Schema.voices.Add("CitizenMale", "BAD NEWS", "Civil Protection catches you down here, it's bad news for the whole railroad.", "vo/canals/boxcar_becareful_c.wav")
Schema.voices.Add("CitizenMale", "NO NO!", "No, No!", "vo/npc/male01/no01.wav")
Schema.voices.Add("CitizenMale", "NOO!", "NOOOO!", "vo/npc/male01/no02.wav")

Schema.voices.Add("CitizenFemale", "HELP ME", "Help me!", "vo/canals/arrest_helpme.wav")
Schema.voices.Add("CitizenFemale", "GET GOING NOW", "You'd better get going now.", "vo/canals/airboat_go_nag01.wav")
Schema.voices.Add("CitizenFemale", "YOU GO ON", "I'm staying put. You go on.", "vo/canals/airboat_go_nag03.wav")
Schema.voices.Add("CitizenFemale", "GET GOING", "Get going!", "vo/canals/arrest_getgoing.wav")
Schema.voices.Add("CitizenFemale", "LOOKING FOR YOU", "They'll be looking for you now.", "vo/canals/arrest_lookingforyou.wav")
Schema.voices.Add("CitizenFemale", "NOTHING YOU CAN DO", "You better run, there's nothing else you can do here.", "vo/canals/arrest_run.wav")
Schema.voices.Add("CitizenFemale", "DIDN'T DO ANYTHING", "Stop! We didn't do anything!", "vo/canals/arrest_stop.wav")
Schema.voices.Add("CitizenFemale", "GO ON", "Go on!", "vo/canals/female01/stn6_go_nag02.wav")
Schema.voices.Add("CitizenFemale", "INCOMING", "Incoming!", "vo/canals/female01/stn6_incoming.wav")
Schema.voices.Add("CitizenFemale", "THEYRE SHELLING US", "They're shelling us!", "vo/canals/female01/stn6_shellingus.wav")

-- coast + eli_lab

Schema.voices.Add("CitizenMale", "HERE COME THE DROPSHIPS", "Oh crap! Here come the dropships!", "vo/coast/barn/male01/crapships.wav")
Schema.voices.Add("CitizenMale", "OFF THE ROAD", "Get off the road!", "vo/coast/barn/male01/getoffroad01.wav")
Schema.voices.Add("CitizenMale", "INCOMING DROPSHIP", "Incoming dropship!", "vo/coast/barn/male01/incomingdropship.wav")
Schema.voices.Add("CitizenMale", "GUNSHIP", "It's a gunship!", "vo/coast/barn/male01/lite_gunship01.wav")
Schema.voices.Add("CitizenMale", "GUNSHIP2", "Gunship!", "vo/coast/barn/male01/lite_gunship02.wav")
Schema.voices.Add("CitizenMale", "YOU MADE IT", "You made it!", "vo/coast/barn/male01/youmadeit.wav")
Schema.voices.Add("CitizenMale", "NO HELP", "No, help!", "vo/coast/bugbait/sandy_help.wav")
Schema.voices.Add("CitizenMale", "YOU THERE", "You there!", "vo/coast/bugbait/sandy_youthere.wav")
Schema.voices.Add("CitizenMale", "FOLLOW ME", "Follow me.", "vo/coast/cardock/le_followme.wav")
Schema.voices.Add("CitizenMale", "GOOD IDEA", "Yeah good idea. Hold on a sec.", "vo/coast/cardock/le_goodidea.wav")
Schema.voices.Add("CitizenMale", "PATCH HIM UP", "Patch him up and get him to the back as soon as he's stable.", "vo/coast/cardock/le_patchhim.wav")
Schema.voices.Add("CitizenMale", "WHOSHURT", "Who's hurt?", "vo/coast/cardock/le_whohurt.wav")
Schema.voices.Add("CitizenMale", "CHEER", "*Cheering.*", "vo/coast/odessa/male01/nlo_cheer01.wav")
Schema.voices.Add("CitizenMale", "CHEER2", "*Cheering.*", "vo/coast/odessa/male01/nlo_cheer02.wav")
Schema.voices.Add("CitizenMale", "CHEER3", "*Cheering.*", "vo/coast/odessa/male01/nlo_cheer03.wav")
Schema.voices.Add("CitizenMale", "CHEER4", "*Cheering.*", "vo/coast/odessa/male01/nlo_cheer03.wav")
Schema.voices.Add("CitizenMale", "DRIVE SAFELY", "Drive safely.", "vo/coast/odessa/male01/nlo_citizen_drivesafe.wav")
Schema.voices.Add("CitizenMale", "NO NO2", "No, Nooo!", "vo/coast/odessa/male01/nlo_cubdeath01.wav")
Schema.voices.Add("CitizenMale", "NO NO3", "No! Noooo!", "vo/coast/odessa/male01/nlo_cubdeath02.wav")
Schema.voices.Add("CitizenMale", "THIS WAY", "This way.", "vo/coast/odessa/male01/stairman_follow01.wav")
Schema.voices.Add("CitizenMale", "GOOD TO KNOW YOU", "Good to know you.", "vo/eli_lab/airlock_cit01.wav")
Schema.voices.Add("CitizenMale", "BETTER GET GOING", "You better get going.", "vo/eli_lab/airlock_cit02.wav")

Schema.voices.Add("CitizenFemale", "HERE COME THE DROPSHIPS", "Oh crap! Here come the dropships!", "vo/coast/barn/female01/crapships.wav")
Schema.voices.Add("CitizenFemale", "OFF THE ROAD", "Get off the road!", "vo/coast/barn/female01/getoffroad01.wav")
Schema.voices.Add("CitizenFemale", "INCOMING DROPSHIP", "Incoming dropship!", "vo/coast/barn/female01/incomingdropship.wav")
Schema.voices.Add("CitizenFemale", "GUNSHIP", "It's a gunship!", "vo/coast/barn/female01/lite_gunship01.wav")
Schema.voices.Add("CitizenFemale", "GUNSHIP2", "Gunship!", "vo/coast/barn/female01/lite_gunship02.wav")
Schema.voices.Add("CitizenFemale", "YOU MADE IT", "You made it!", "vo/coast/barn/female01/youmadeit.wav")
Schema.voices.Add("CitizenFemale", "CHEER", "*Cheering.*", "vo/coast/odessa/female01/nlo_cheer01.wav")
Schema.voices.Add("CitizenFemale", "CHEER2", "*Cheering.*", "vo/coast/odessa/female01/nlo_cheer02.wav")
Schema.voices.Add("CitizenFemale", "CHEER3", "*Cheering.*", "vo/coast/odessa/female01/nlo_cheer03.wav")
Schema.voices.Add("CitizenFemale", "DRIVE SAFELY", "Drive safely.", "vo/coast/odessa/female01/nlo_citizen_drivesafe.wav")
Schema.voices.Add("CitizenFemale", "NO NO2", "No, Nooo!", "vo/coast/odessa/female01/nlo_cubdeath01.wav")
Schema.voices.Add("CitizenFemale", "NO NO3", "Nooo!", "vo/coast/odessa/female01/nlo_cubdeath02.wav")
Schema.voices.Add("CitizenFemale", "THIS WAY", "This way.", "vo/coast/odessa/female01/stairman_follow01.wav")

-- npc

Schema.voices.Add("CitizenMale", "AMMO", "Here, ammo!", "vo/npc/male01/ammo03.wav")
Schema.voices.Add("CitizenMale", "AMMO2", "Take some ammo!", "vo/npc/male01/ammo04.wav")
Schema.voices.Add("CitizenMale", "AMMO3", "Take some ammo!", "vo/npc/male01/ammo05.wav")
Schema.voices.Add("CitizenMale", "YOU ALL OVER", "That's you all over.", "vo/npc/male01/answer01.wav")
Schema.voices.Add("CitizenMale", "WONT HOLD IT AGAINST YOU", "I wont hold it against you.", "vo/npc/male01/answer02.wav")
Schema.voices.Add("CitizenMale", "FIGURES", "Figures.", "vo/npc/male01/answer03.wav")
Schema.voices.Add("CitizenMale", "TRY NOT TO DWELL", "Try not to dwell on it.", "vo/npc/male01/answer04.wav")
Schema.voices.Add("CitizenMale", "CAN WE TALK LATER", "Can we talk about this later?", "vo/npc/male01/answer05.wav")
Schema.voices.Add("CitizenMale", "SAME HERE", "Same here.", "vo/npc/male01/answer07.wav")
Schema.voices.Add("CitizenMale", "KNOW WHAT YOU MEAN", "Know what you mean.", "vo/npc/male01/answer08.wav")
Schema.voices.Add("CitizenMale", "TALKING TO YOURSELF", "You're taking to yourself again.", "vo/npc/male01/answer09.wav")
Schema.voices.Add("CitizenMale", "WOULDNT SAY TOO LOUD", "I wouldn't say that too loud.", "vo/npc/male01/answer10.wav")
Schema.voices.Add("CitizenMale", "TOMB STONE", "I'll put it on your tombstone.", "vo/npc/male01/answer11.wav")
Schema.voices.Add("CitizenMale", "BEAR THINKING ABOUT", "Doesn't bear thinking about.", "vo/npc/male01/answer12.wav")
Schema.voices.Add("CitizenMale", "IM WITH YOU", "I'm with you.", "vo/npc/male01/answer13.wav")
Schema.voices.Add("CitizenMale", "YOU AND ME BOTH", "You and me both.", "vo/npc/male01/answer14.wav")
Schema.voices.Add("CitizenMale", "ONE WAY", "That's... one way of looking at it.", "vo/npc/male01/answer15.wav")
Schema.voices.Add("CitizenMale", "ORIGINAL THOUGHT", "Have you ever had an original thought?", "vo/npc/male01/answer16.wav")
Schema.voices.Add("CitizenMale", "SHUT UP", "I'm not even gonna tell you to shut up.", "vo/npc/male01/answer17.wav")
Schema.voices.Add("CitizenMale", "CONCENTRATE", "Let's concentrate on the task at hand.", "vo/npc/male01/answer18.wav")
Schema.voices.Add("CitizenMale", "MIND ON YOUR WORK", "Keep your mind on your work.", "vo/npc/male01/answer19.wav")
Schema.voices.Add("CitizenMale", "IN THE GUTTER", "Your mind is in the gutter.", "vo/npc/male01/answer20.wav")
Schema.voices.Add("CitizenMale", "DON'T BE SO SURE", "Don't be so sure of that.", "vo/npc/male01/answer21.wav")
Schema.voices.Add("CitizenMale", "YOU NEVER KNOW", "You never know.", "vo/npc/male01/answer22.wav")
Schema.voices.Add("CitizenMale", "NEVER CAN'T TELL", "Never can't tell.", "vo/npc/male01/answer23.wav")
Schema.voices.Add("CitizenMale", "TELLING ME", "Why are you telling me?", "vo/npc/male01/answer24.wav")
Schema.voices.Add("CitizenMale", "HOW ABOUT THAT", "How about that.", "vo/npc/male01/answer25.wav")
Schema.voices.Add("CitizenMale", "MORE INFORMATION", "That's more information than I require.", "vo/npc/male01/answer26.wav")
Schema.voices.Add("CitizenMale", "WANNA BET", "Wanna bet?", "vo/npc/male01/answer27.wav")
Schema.voices.Add("CitizenMale", "WISH I HAD A DIME", "I wish I had a dime for every time somebody said that.", "vo/npc/male01/answer28.wav")
Schema.voices.Add("CitizenMale", "WHAT AM I SUPPOSED TO DO", "What am I supposed to do about it?", "vo/npc/male01/answer29.wav")
Schema.voices.Add("CitizenMale", "TALKING TO ME", "You talking to me?", "vo/npc/male01/answer30.wav")
Schema.voices.Add("CitizenMale", "NIP THAT TALK", "You should nip that kind of talk in the bud.", "vo/npc/male01/answer31.wav")
Schema.voices.Add("CitizenMale", "RIGHT ON", "Right on.", "vo/npc/male01/answer32.wav")
Schema.voices.Add("CitizenMale", "NO ARGUMENT", "No argument there.", "vo/npc/male01/answer33.wav")
Schema.voices.Add("CitizenMale", "DON'T FORGET HAWAII", "Don't forget Hawaii", "vo/npc/male01/answer34.wav")
Schema.voices.Add("CitizenMale", "DON'T LET IT GET TO YOU", "Try not to let it get to you.", "vo/npc/male01/answer35.wav")
Schema.voices.Add("CitizenMale", "WOULDN'T BE THE FIRST TIME", "Wouldn't be the first time.", "vo/npc/male01/answer36.wav")
Schema.voices.Add("CitizenMale", "SURE ABOUT THAT", "You sure about that?", "vo/npc/male01/answer37.wav")
Schema.voices.Add("CitizenMale", "LEAVE IT", "Leave it alone.", "vo/npc/male01/answer38.wav")
Schema.voices.Add("CitizenMale", "ENOIGH OUTTA YOU", "That's enough outta you.", "vo/npc/male01/answer39.wav")
Schema.voices.Add("CitizenMale", "FIRST TIME FOR EVERYTHING", "There's a first time for everything.", "vo/npc/male01/answer40.wav")
Schema.voices.Add("CitizenMale", "BEHIND YOU", "Behind you!", "vo/npc/male01/behindyou01.wav")
Schema.voices.Add("CitizenMale", "BEHIND YOU2", "Behind you!", "vo/npc/male01/behindyou02.wav")
Schema.voices.Add("CitizenMale", "IM BUSY", "Can't you see I'm busy?", "vo/npc/male01/busy02.wav")
Schema.voices.Add("CitizenMale", "SUPPLIES", "Hey down there! Supplies!", "vo/npc/male01/cit_dropper01.wav")
Schema.voices.Add("CitizenMale", "LOOK OUT BELOW", "Look out below!", "vo/npc/male01/cit_dropper04.wav")
Schema.voices.Add("CitizenMale", "CIVIL PROTECTION", "Civil Protection!", "vo/npc/male01/civilprotection01.wav")
Schema.voices.Add("CitizenMale", "CIVILP ROTECTION2", "Civil Protection!", "vo/npc/male01/civilprotection02.wav")
Schema.voices.Add("CitizenMale", "COMBINE", "Combine!", "vo/npc/male01/combine01.wav")
Schema.voices.Add("CitizenMale", "COMBINE2", "Combine!", "vo/npc/male01/combine02.wav")
Schema.voices.Add("CitizenMale", "RELOADING", "Cover me while I reload!", "vo/npc/male01/coverwhilereload01.wav")
Schema.voices.Add("CitizenMale", "RELOADING2", "Cover me while I reload!", "vo/npc/male01/coverwhilereload02.wav")
Schema.voices.Add("CitizenMale", "CPS", "CPs!", "vo/npc/male01/cps01.wav")
Schema.voices.Add("CitizenMale", "CPS2", "CPs!", "vo/npc/male01/cps02.wav")
Schema.voices.Add("CitizenMale", "DOING SOMETHING", "Shouldn't we be doing something?", "vo/npc/male01/doingsomething.wav")
Schema.voices.Add("CitizenMale", "EVEN THE ODDS", "Let's even the odds a little.", "vo/npc/male01/evenodds.wav")
Schema.voices.Add("CitizenMale", "EXCUSE ME", "Excuse me.", "vo/npc/male01/excuseme01.wav")
Schema.voices.Add("CitizenMale", "EXCUSE ME2", "Excuse me.", "vo/npc/male01/excuseme02.wav")
Schema.voices.Add("CitizenMale", "FANTASTIC", "Fantastic.", "vo/npc/male01/fantastic01.wav")
Schema.voices.Add("CitizenMale", "FANTASTIC2", "Fantastic.", "vo/npc/male01/fantastic02.wav")
Schema.voices.Add("CitizenMale", "FINALLY", "Finally.", "vo/npc/male01/finally.wav")
Schema.voices.Add("CitizenMale", "GET DOWN", "Get down!", "vo/npc/male01/getdown02.wav")
Schema.voices.Add("CitizenMale", "GET GOING SOON", "Are we gonna get going soon?", "vo/npc/male01/getgoingsoon.wav")
Schema.voices.Add("CitizenMale", "GET THE HELL OUTTA HERE", "Get the hell outta here!", "vo/npc/male01/gethellout.wav")
Schema.voices.Add("CitizenMale", "GOOD GOD", "Good god!", "vo/npc/male01/goodgod.wav")
Schema.voices.Add("CitizenMale", "NOW WHAT", "Now what?", "vo/npc/male01/gordead_ans01.wav")
Schema.voices.Add("CitizenMale", "GOING SOWELL", "And things were going so well.", "vo/npc/male01/gordead_ans02.wav")
Schema.voices.Add("CitizenMale", "DON'T TELL ME", "Don't tell me.", "vo/npc/male01/gordead_ans03.wav")
Schema.voices.Add("CitizenMale", "OH GOD", "Oh God.", "vo/npc/male01/gordead_ans04.wav")
Schema.voices.Add("CitizenMale", "OH NO", "Oh no.", "vo/npc/male01/gordead_ans05.wav")
Schema.voices.Add("CitizenMale", "PLEASE NO", "Please, no.", "vo/npc/male01/gordead_ans06.wav")
Schema.voices.Add("CitizenMale", "IF YOU DARE SAY", "If you dare say 'That's gotta hurt', I'll kill you.", "vo/npc/male01/gordead_ans07.wav")
Schema.voices.Add("CitizenMale", "SHOULD WE BURY HIM", "Should we bury him here?", "vo/npc/male01/gordead_ans08.wav")
Schema.voices.Add("CitizenMale", "SPREAD THE WORD", "Spread the word.", "vo/npc/male01/gordead_ans10.wav")
Schema.voices.Add("CitizenMale", "WHATS THE USE", "What's the use?", "vo/npc/male01/gordead_ans11.wav")
Schema.voices.Add("CitizenMale", "WHATS THE POINT", "What's the point?", "vo/npc/male01/gordead_ans12.wav")
Schema.voices.Add("CitizenMale", "WHY GO ON", "Why go on?", "vo/npc/male01/gordead_ans13.wav")
Schema.voices.Add("CitizenMale", "WERE DONE FOR", "We're done for.", "vo/npc/male01/gordead_ans14.wav")
Schema.voices.Add("CitizenMale", "NOW WHAT2", "Well, now what?", "vo/npc/male01/gordead_ans15.wav")
Schema.voices.Add("CitizenMale", "DONE THIS BEFORE", "He's done this before, he'll be ok.", "vo/npc/male01/gordead_ans18.wav")
Schema.voices.Add("CitizenMale", "IM GONNA BE SICK", "I'm gonna be sick.", "vo/npc/male01/gordead_ans19.wav")
Schema.voices.Add("CitizenMale", "HES DEAD", "He's dead.", "vo/npc/male01/gordead_ques01.wav")
Schema.voices.Add("CitizenMale", "WAY TO GO", "What a way to go.", "vo/npc/male01/gordead_ques02.wav")
Schema.voices.Add("CitizenMale", "THIS CAN'T BE", "This can't be.", "vo/npc/male01/gordead_ques06.wav")
Schema.voices.Add("CitizenMale", "HES DEAD2", "Look, he's dead!", "vo/npc/male01/gordead_ques07.wav")
Schema.voices.Add("CitizenMale", "THIS IS BAD", "This is bad.", "vo/npc/male01/gordead_ques10.wav")
Schema.voices.Add("CitizenMale", "NOT SUPPOSED TO END", "It's not supposed to end like this!", "vo/npc/male01/gordead_ques14.wav")
Schema.voices.Add("CitizenMale", "WHAT NOW", "What now?", "vo/npc/male01/gordead_ques16.wav")
Schema.voices.Add("CitizenMale", "GOT ONE", "Got one!", "vo/npc/male01/gotone01.wav")
Schema.voices.Add("CitizenMale", "GOT ONE2", "I got one!", "vo/npc/male01/gotone02.wav")
Schema.voices.Add("CitizenMale", "RELOADING3", "Gotta reload.", "vo/npc/male01/gottareload01.wav")
Schema.voices.Add("CitizenMale", "GUNSHIP3", "Gunship!", "vo/npc/male01/gunship02.wav")
Schema.voices.Add("CitizenMale", "HEADCRABS", "Headcrabs!", "vo/npc/male01/headcrabs01.wav")
Schema.voices.Add("CitizenMale", "HEADCRABS2", "Headcrabs!", "vo/npc/male01/headcrabs02.wav")
Schema.voices.Add("CitizenMale", "HEADS UP", "Heads up!", "vo/npc/male01/headsup01.wav")
Schema.voices.Add("CitizenMale", "HEADS UP2", "Heads up!", "vo/npc/male01/headsup02.wav")
Schema.voices.Add("CitizenMale", "MEDKIT", "Take this medkit.", "vo/npc/male01/health01.wav")
Schema.voices.Add("CitizenMale", "MEDKIT2", "Take this medkit.", "vo/npc/male01/health02.wav")
Schema.voices.Add("CitizenMale", "MEDKIT3", "Take this medkit.", "vo/npc/male01/health03.wav")
Schema.voices.Add("CitizenMale", "MEDKIT4", "Here, have a medkit.", "vo/npc/male01/health04.wav")
Schema.voices.Add("CitizenMale", "MEDKIT5", "Here, patch yourself up.", "vo/npc/male01/health05.wav")
Schema.voices.Add("CitizenMale", "HELP", "Help!", "vo/npc/male01/help01.wav")
Schema.voices.Add("CitizenMale", "HERE COME THE HACKS", "Here come the hacks!", "vo/npc/male01/herecomehacks01.wav")
Schema.voices.Add("CitizenMale", "HERE COME THE HACKS2", "Here come the hacks!", "vo/npc/male01/herecomehacks02.wav")
Schema.voices.Add("CitizenMale", "HERE THEY COME", "Here they come!", "vo/npc/male01/heretheycome01.wav")
Schema.voices.Add("CitizenMale", "HI", "Hi.", "vo/npc/male01/hi01.wav")
Schema.voices.Add("CitizenMale", "HI2", "Hi.", "vo/npc/male01/hi02.wav")
Schema.voices.Add("CitizenMale", "HIT IN THE GUT", "Hit in the gut.", "vo/npc/male01/hitingut01.wav")
Schema.voices.Add("CitizenMale", "HIT IN THE GUT2", "Hit in the gut.", "vo/npc/male01/hitingut02.wav")
Schema.voices.Add("CitizenMale", "HOLD DOWN THIS SPOT", "I'm gonna stay and hold down this spot.", "vo/npc/male01/holddownspot01.wav")
Schema.voices.Add("CitizenMale", "HOLD DOWN THIS SPOT2", "I'm gonna stay and hold down this spot.", "vo/npc/male01/holddownspot02.wav")
Schema.voices.Add("CitizenMale", "ILL STAY HERE", "I'll stay here.", "vo/npc/male01/illstayhere01.wav")
Schema.voices.Add("CitizenMale", "IM HURT", "I'm hurt.", "vo/npc/male01/imhurt01.wav")
Schema.voices.Add("CitizenMale", "IM HURT2", "I'm hurt.", "vo/npc/male01/imhurt02.wav")
Schema.voices.Add("CitizenMale", "IM STICKING HERE", "I'm sticking here.", "vo/npc/male01/imstickinghere01.wav")
Schema.voices.Add("CitizenMale", "IN COMING2", "Incoming!", "vo/npc/male01/incoming02.wav")
Schema.voices.Add("CitizenMale", "ITS A MANHACK", "It's a manhack!", "vo/npc/male01/itsamanhack01.wav")
Schema.voices.Add("CitizenMale", "ITS A MANKACK2", "It's a manhack!", "vo/npc/male01/itsamanhack02.wav")
Schema.voices.Add("CitizenMale", "LEAD THE WAY", "You lead the way!", "vo/npc/male01/leadtheway01.wav")
Schema.voices.Add("CitizenMale", "LEAD THE WAY2", "Lead the way!", "vo/npc/male01/leadtheway02.wav")
Schema.voices.Add("CitizenMale", "LETS GO", "Let's go!", "vo/npc/male01/letsgo01.wav")
Schema.voices.Add("CitizenMale", "LETS GO2", "Let's go!", "vo/npc/male01/letsgo02.wav")
Schema.voices.Add("CitizenMale", "LIKE THAT", "Like that?!", "vo/npc/male01/likethat.wav")
Schema.voices.Add("CitizenMale", "CORNER", "I've got my little corner and I'm sticking to it.", "vo/npc/male01/littlecorner01.wav")
Schema.voices.Add("CitizenMale", "GROAN", "*Groan*", "vo/npc/male01/moan01.wav")
Schema.voices.Add("CitizenMale", "GROAN2", "*Groan*", "vo/npc/male01/moan02.wav")
Schema.voices.Add("CitizenMale", "GROAN3", "*Groan*", "vo/npc/male01/moan03.wav")
Schema.voices.Add("CitizenMale", "GROAN4", "*Groan*", "vo/npc/male01/moan04.wav")
Schema.voices.Add("CitizenMale", "GROAN5", "*Groan*", "vo/npc/male01/moan05.wav")
Schema.voices.Add("CitizenMale", "MY ARM", "My arm.", "vo/npc/male01/myarm01.wav")
Schema.voices.Add("CitizenMale", "MY ARM2", "My arm.", "vo/npc/male01/myarm02.wav")
Schema.voices.Add("CitizenMale", "MY GUT", "My gut.", "vo/npc/male01/mygut02.wav")
Schema.voices.Add("CitizenMale", "MY LEG", "My leg.", "vo/npc/male01/myleg01.wav")
Schema.voices.Add("CitizenMale", "MY LEG2", "My leg.", "vo/npc/male01/myleg02.wav")
Schema.voices.Add("CitizenMale", "NICE", "Nice.", "vo/npc/male01/nice.wav")
Schema.voices.Add("CitizenMale", "OH NO2", "Oh no.", "vo/npc/male01/ohno.wav")
Schema.voices.Add("CitizenMale", "OK", "Ok.", "vo/npc/male01/ok01.wav")
Schema.voices.Add("CitizenMale", "OK2", "Ok.", "vo/npc/male01/ok02.wav")
Schema.voices.Add("CitizenMale", "OK IM READY", "Ok, I'm ready.", "vo/npc/male01/okimready01.wav")
Schema.voices.Add("CitizenMale", "OK IM READY2", "Ok, I'm ready.", "vo/npc/male01/okimready02.wav")
Schema.voices.Add("CitizenMale", "OK IM READY3", "Ok, I'm ready!", "vo/npc/male01/okimready03.wav")
Schema.voices.Add("CitizenMale", "ONE FOR ME", "One for me and one for me.", "vo/npc/male01/oneforme.wav")
Schema.voices.Add("CitizenMale", "OUT OF YOUR WAY", "Let me get out of your way.", "vo/npc/male01/outofyourway02.wav")
Schema.voices.Add("CitizenMale", "HEY OVER HERE", "Hey over here!", "vo/npc/male01/overhere01.wav")
Schema.voices.Add("CitizenMale", "OVER THERE", "Over there!", "vo/npc/male01/overthere01.wav")
Schema.voices.Add("CitizenMale", "OVER THERE2", "Over there!", "vo/npc/male01/overthere02.wav")
Schema.voices.Add("CitizenMale", "OW", "Ow!", "vo/npc/male01/ow01.wav")
Schema.voices.Add("CitizenMale", "OW2", "Ow!", "vo/npc/male01/ow02.wav")
Schema.voices.Add("CitizenMale", "PARDON ME", "Pardon me.", "vo/npc/male01/pardonme01.wav")
Schema.voices.Add("CitizenMale", "PARDON ME2", "Pardon me.", "vo/npc/male01/pardonme02.wav")
Schema.voices.Add("CitizenMale", "EVER GONNA END", "I don't think this war is ever gonna end.", "vo/npc/male01/question01.wav")
Schema.voices.Add("CitizenMale", "INSURANCE", "To think, all I used to want to do was sell insurance.", "vo/npc/male01/question02.wav")
Schema.voices.Add("CitizenMale", "DON'T DREAM", "I don't dream anymore.", "vo/npc/male01/question03.wav")
Schema.voices.Add("CitizenMale", "WHEN THIS IS OVER", "When this is all over I'm...aw, who am I kidding?", "vo/npc/male01/question04.wav")
Schema.voices.Add("CitizenMale", "DEJAVU", "Woah, Deja vu.", "vo/npc/male01/question05.wav")
Schema.voices.Add("CitizenMale", "CHEESE", "Sometimes, I dream about cheese.", "vo/npc/male01/question06.wav")
Schema.voices.Add("CitizenMale", "FREEDOM", "You smell that? It's freedom!", "vo/npc/male01/question07.wav")
Schema.voices.Add("CitizenMale", "EAT A HORSE", "I could eat a horse, hooves and all.", "vo/npc/male01/question09.wav")
Schema.voices.Add("CitizenMale", "CAN'T BELIEVE THIS DAY", "I can't believe this day has finally come!", "vo/npc/male01/question10.wav")
Schema.voices.Add("CitizenMale", "NOT PART OF PLAN", "I'm pretty sure this isn't part of the plan.", "vo/npc/male01/question11.wav")
Schema.voices.Add("CitizenMale", "WORSE NOT BETTER", "Looks to me things are getting worse, not better.", "vo/npc/male01/question12.wav")
Schema.voices.Add("CitizenMale", "LIVE MY LIFE ALL OVER", "If I could live my life all over again.", "vo/npc/male01/question13.wav")
Schema.voices.Add("CitizenMale", "WHAT THAT REMINDS ME", "I'm not even gonna tell you what that reminds me of.", "vo/npc/male01/question14.wav")
Schema.voices.Add("CitizenMale", "STALKER OUT OF ME", "They're never gonna make a stalker out of me.", "vo/npc/male01/question15.wav")
Schema.voices.Add("CitizenMale", "CHANGE IS IN THE AIR", "Finally, change is in the air!", "vo/npc/male01/question16.wav")
Schema.voices.Add("CitizenMale", "YOU FEEL IT", "You feel it? I feel it!", "vo/npc/male01/question17.wav")
Schema.voices.Add("CitizenMale", "DON'T FEEL ANYTHING", "I don't feel anything anymore.", "vo/npc/male01/question18.wav")
Schema.voices.Add("CitizenMale", "SHOWER", "I can't remember the last time I had a shower.", "vo/npc/male01/question19.wav")
Schema.voices.Add("CitizenMale", "BAD MEMORY", "Some day, this will all be a bad memory.", "vo/npc/male01/question20.wav")
Schema.voices.Add("CitizenMale", "BETTING", "I'm not a betting man, but the odds are not good.", "vo/npc/male01/question21.wav")
Schema.voices.Add("CitizenMale", "CARE WHAT I THINK", "Doesn't anyone care what I think?", "vo/npc/male01/question22.wav")
Schema.voices.Add("CitizenMale", "TUNE", "I can't get this tune out of my head. *Whistling.*", "vo/npc/male01/question23.wav")
Schema.voices.Add("CitizenMale", "ONE OF THOSE DAYS", "I just knew it was gonna be one of those days.", "vo/npc/male01/question25.wav")
Schema.voices.Add("CitizenMale", "BULLSHIT", "This is bullshit.", "vo/npc/male01/question26.wav")
Schema.voices.Add("CitizenMale", "ATE SOMETHING BAD", "I think I ate something bad.", "vo/npc/male01/question27.wav")
Schema.voices.Add("CitizenMale", "HUNGRY", "God, I'm hungry.", "vo/npc/male01/question28.wav")
Schema.voices.Add("CitizenMale", "IM GONNAMATE", "When this is all over, I'm gonna mate.", "vo/npc/male01/question29.wav")
Schema.voices.Add("CitizenMale", "NO KIDS", "I'm glad there's no kids around to see this.", "vo/npc/male01/question30.wav")
Schema.voices.Add("CitizenMale", "CAN'T REMEMBER", "I can't remember the last time I had... well, anything.", "vo/npc/male01/question31.wav")
Schema.voices.Add("CitizenMale", "READY WHEN YOU ARE", "Ready when you are!", "vo/npc/male01/readywhenyouare01.wav")
Schema.voices.Add("CitizenMale", "READY WHEN YOU ARE2", "Ready when you are!", "vo/npc/male01/readywhenyouare02.wav")
Schema.voices.Add("CitizenMale", "RUN FOR YOUR LIFE", "Run for your life!", "vo/npc/male01/runforyourlife01.wav")
Schema.voices.Add("CitizenMale", "RUN FOR YOUR LIFE2", "Run for your life!", "vo/npc/male01/runforyourlife02.wav")
Schema.voices.Add("CitizenMale", "RUN FOR YOUR LIFE3", "Run for your life!", "vo/npc/male01/runforyourlife03.wav")
Schema.voices.Add("CitizenMale", "SCANNERS", "Scanners!", "vo/npc/male01/scanners01.wav")
Schema.voices.Add("CitizenMale", "SCANNERS2", "Scanners!", "vo/npc/male01/scanners02.wav")
Schema.voices.Add("CitizenMale", "SORRY", "Sorry.", "vo/npc/male01/sorry01.wav")
Schema.voices.Add("CitizenMale", "SORRY2", "Sorry.", "vo/npc/male01/sorry02.wav")
Schema.voices.Add("CitizenMale", "SORRY3", "Sorry.", "vo/npc/male01/sorry03.wav")
Schema.voices.Add("CitizenMale", "WHATEVER YOU SAY", "Whatever you say.", "vo/npc/male01/squad_affirm03.wav")
Schema.voices.Add("CitizenMale", "OK IM GOING", "Ok, I'm going.", "vo/npc/male01/squad_affirm04.wav")
Schema.voices.Add("CitizenMale", "HERE GOES", "Here goes.", "vo/npc/male01/squad_affirm05.wav")
Schema.voices.Add("CitizenMale", "HERE GOES NOTHING", "Here goes nothing.", "vo/npc/male01/squad_affirm06.wav")
Schema.voices.Add("CitizenMale", "HERE WE COME", "Here we come!", "vo/npc/male01/squad_approach02.wav")
Schema.voices.Add("CitizenMale", "ON OUR WAY", "On our way!", "vo/npc/male01/squad_approach03.wav")
Schema.voices.Add("CitizenMale", "COMING", "Coming!", "vo/npc/male01/squad_approach04.wav")
Schema.voices.Add("CitizenMale", "THIS WAY GANG", "This way gang!", "vo/npc/male01/squad_away01.wav")
Schema.voices.Add("CitizenMale", "OVER HERE", "Over here!", "vo/npc/male01/squad_away02.wav")
Schema.voices.Add("CitizenMale", "FOLLOW ME", "Follow me!", "vo/npc/male01/squad_away03.wav")
Schema.voices.Add("CitizenMale", "COME ON EVERYBODY", "Come on everybody!", "vo/npc/male01/squad_follow02.wav")
Schema.voices.Add("CitizenMale", "LETS GET MOVING", "Let's get moving.", "vo/npc/male01/squad_follow03.wav")
Schema.voices.Add("CitizenMale", "WAIT FOR US", "Wait for us!", "vo/npc/male01/squad_reinforce_group04.wav")
Schema.voices.Add("CitizenMale", "WAIT FOR ME", "Wait for me!", "vo/npc/male01/squad_reinforce_single04.wav")
Schema.voices.Add("CitizenMale", "GASP", "*Gasp.*", "vo/npc/male01/startle01.wav")
Schema.voices.Add("CitizenMale", "GASP2", "*Gasp.*", "vo/npc/male01/startle02.wav")
Schema.voices.Add("CitizenMale", "STRIDER", "Strider!", "vo/npc/male01/strider.wav")
Schema.voices.Add("CitizenMale", "RUN", "Run!", "vo/npc/male01/strider_run.wav")
Schema.voices.Add("CitizenMale", "TAKE COVER", "Take cover!", "vo/npc/male01/takecover02.wav")
Schema.voices.Add("CitizenMale", "THIS WILL DO NICELY", "This will do nicely.", "vo/npc/male01/thislldonicely01.wav")
Schema.voices.Add("CitizenMale", "UH OH", "Uh oh.", "vo/npc/male01/uhoh.wav")
Schema.voices.Add("CitizenMale", "UP THERE", "Up there!", "vo/npc/male01/upthere01.wav")
Schema.voices.Add("CitizenMale", "UP THERE2", "Up there!", "vo/npc/male01/upthere02.wav")
Schema.voices.Add("CitizenMale", "MUMBOJUMBO", "Enough of your mumbo jumbo.", "vo/npc/male01/vanswer01.wav")
Schema.voices.Add("CitizenMale", "DAMN VORTS", "Damn vorts.", "vo/npc/male01/vanswer02.wav")
Schema.voices.Add("CitizenMale", "NOT SURE HOW TO TAKE THAT", "I'm not sure how to take that.", "vo/npc/male01/vanswer03.wav")
Schema.voices.Add("CitizenMale", "TAKE THAT PERSONALLY", "Should I take that personally?", "vo/npc/male01/vanswer04.wav")
Schema.voices.Add("CitizenMale", "SPEAK ENGLISH", "Speak English.", "vo/npc/male01/vanswer05.wav")
Schema.voices.Add("CitizenMale", "GOT FROM ME", "You got that from me.", "vo/npc/male01/vanswer06.wav")
Schema.voices.Add("CitizenMale", "WE PUT UP WITH YOU", "That's why we put up with you.", "vo/npc/male01/vanswer07.wav")
Schema.voices.Add("CitizenMale", "PUT IT BETTER MYSELF", "Couldn't have put it better myself.", "vo/npc/male01/vanswer08.wav")
Schema.voices.Add("CitizenMale", "ALMOST MADE SENSE", "That... almost made sense.", "vo/npc/male01/vanswer09.wav")
Schema.voices.Add("CitizenMale", "ALMOST UNDERSTOOD", "Something must be wrong with me, I almost understood that.", "vo/npc/male01/vanswer10.wav")
Schema.voices.Add("CitizenMale", "GETTING USED TO VORTS", "I guess I'm getting used to you vorts.", "vo/npc/male01/vanswer11.wav")
Schema.voices.Add("CitizenMale", "VORT PHILOSOPHY", "None of your vort philosoply.", "vo/npc/male01/vanswer12.wav")
Schema.voices.Add("CitizenMale", "KILLING ME", "Stop, you're killing me.", "vo/npc/male01/vanswer13.wav")
Schema.voices.Add("CitizenMale", "DESERVE THIS", "What did I do to deserve this?", "vo/npc/male01/vanswer14.wav")
Schema.voices.Add("CitizenMale", "STOP LOOKING", "Stop looking at me like that.", "vo/npc/male01/vquestion01.wav")
Schema.voices.Add("CitizenMale", "NEVER GET USED TO", "Some things I just never get used to.", "vo/npc/male01/vquestion02.wav")
Schema.voices.Add("CitizenMale", "HOW YOU THINGS", "I don't know how you things have survived as long as you have.", "vo/npc/male01/vquestion03.wav")
Schema.voices.Add("CitizenMale", "HOW I ENDED UP", "Sometimes I wonder how I ended up with you.", "vo/npc/male01/vquestion04.wav")
Schema.voices.Add("CitizenMale", "YOURE ALRIGHT VORTY", "You're all right vorty.", "vo/npc/male01/vquestion05.wav")
Schema.voices.Add("CitizenMale", "VORTS ARENT HALF BAD", "You vorts aren't half bad.", "vo/npc/male01/vquestion06.wav")
Schema.voices.Add("CitizenMale", "PALS WITH A VORT", "If anyone would have told me I'd be pals with a vortigaunt...", "vo/npc/male01/vquestion07.wav")
Schema.voices.Add("CitizenMale", "WAITING FOR SOMEBODY", "You waiting for somebody?", "vo/npc/male01/waitingsomebody.wav")
Schema.voices.Add("CitizenMale", "WATCH OUT", "Watch out!", "vo/npc/male01/watchout.wav")
Schema.voices.Add("CitizenMale", "WHATCH WHAT YOURE DOING", "Watch what you're doing!", "vo/npc/male01/watchwhat.wav")
Schema.voices.Add("CitizenMale", "WE TRUSTED YOU", "We trusted you!", "vo/npc/male01/wetrustedyou01.wav")
Schema.voices.Add("CitizenMale", "WE TRUSTED YOU2", "We trusted you!", "vo/npc/male01/wetrustedyou02.wav")
Schema.voices.Add("CitizenMale", "WHOOPS", "Whoops.", "vo/npc/male01/whoops01.wav")
Schema.voices.Add("CitizenMale", "YEAH", "Yeah.", "vo/npc/male01/yeah02.wav")
Schema.voices.Add("CitizenMale", "BETTER RELOAD", "You better reload.", "vo/npc/male01/youdbetterreload01.wav")
Schema.voices.Add("CitizenMale", "YOU GOT IT", "You got it.", "vo/npc/male01/yougotit02.wav")
Schema.voices.Add("CitizenMale", "ZOMBIES", "Zombies!", "vo/npc/male01/zombies01.wav")
Schema.voices.Add("CitizenMale", "ZOMBIES2", "Zombies!", "vo/npc/male01/zombies02.wav")

Schema.voices.Add("CitizenFemale", "AMMO", "Here, ammo!", "vo/npc/female01/ammo03.wav")
Schema.voices.Add("CitizenFemale", "AMMO2", "Take some ammo!", "vo/npc/female01/ammo04.wav")
Schema.voices.Add("CitizenFemale", "AMMO3", "Take some ammo!", "vo/npc/female01/ammo05.wav")
Schema.voices.Add("CitizenFemale", "YOU ALL OVER", "That's you all over.", "vo/npc/female01/answer01.wav")
Schema.voices.Add("CitizenFemale", "WONT HOLD IT AGAINST", "I wont hold it against you.", "vo/npc/female01/answer02.wav")
Schema.voices.Add("CitizenFemale", "FIGURES", "Figures.", "vo/npc/female01/answer03.wav")
Schema.voices.Add("CitizenFemale", "TRY NOT TO DWELL", "Try not to dwell on it.", "vo/npc/female01/answer04.wav")
Schema.voices.Add("CitizenFemale", "CANWETALKLATER", "Can we talk about this later?", "vo/npc/female01/answer05.wav")
Schema.voices.Add("CitizenFemale", "SAMEHERE", "Same here.", "vo/npc/female01/answer07.wav")
Schema.voices.Add("CitizenFemale", "KNOW WHAT YOU MEAN", "Know what you mean.", "vo/npc/female01/answer08.wav")
Schema.voices.Add("CitizenFemale", "TALKING TO YOURSELF", "You're taking to yourself again.", "vo/npc/female01/answer09.wav")
Schema.voices.Add("CitizenFemale", "WOULDNT SAY TOO LOUD", "I wouldn't say that too loud.", "vo/npc/female01/answer10.wav")
Schema.voices.Add("CitizenFemale", "TOMB STONE", "I'll put it on your tombstone.", "vo/npc/female01/answer11.wav")
Schema.voices.Add("CitizenFemale", "BEAR THINKING ABOUT", "Doesn't bear thinking about.", "vo/npc/female01/answer12.wav")
Schema.voices.Add("CitizenFemale", "IM WITH YOU", "I'm with you.", "vo/npc/female01/answer13.wav")
Schema.voices.Add("CitizenFemale", "YOU AND ME BOTH", "You and me both.", "vo/npc/female01/answer14.wav")
Schema.voices.Add("CitizenFemale", "ONE WAY", "That's... one way of looking at it.", "vo/npc/female01/answer15.wav")
Schema.voices.Add("CitizenFemale", "ORIGINAL THOUGHT", "Have you ever had an original thought?", "vo/npc/female01/answer16.wav")
Schema.voices.Add("CitizenFemale", "SHUT UP", "I'm not even gonna tell you to shut up.", "vo/npc/female01/answer17.wav")
Schema.voices.Add("CitizenFemale", "CONCENTRATE", "Let's concentrate on the task at hand.", "vo/npc/female01/answer18.wav")
Schema.voices.Add("CitizenFemale", "MIND ON YOUR WORK", "Keep your mind on your work.", "vo/npc/female01/answer19.wav")
Schema.voices.Add("CitizenFemale", "IN THE GUTTER", "Your mind is in the gutter.", "vo/npc/female01/answer20.wav")
Schema.voices.Add("CitizenFemale", "DON'T BE SO SURE", "Don't be so sure of that.", "vo/npc/female01/answer21.wav")
Schema.voices.Add("CitizenFemale", "YOU NEVER KNOW", "You never know.", "vo/npc/female01/answer22.wav")
Schema.voices.Add("CitizenFemale", "NEVER CAN'T TELL", "Never can't tell.", "vo/npc/female01/answer23.wav")
Schema.voices.Add("CitizenFemale", "TELLING ME", "Why are you telling me?", "vo/npc/female01/answer24.wav")
Schema.voices.Add("CitizenFemale", "HOW ABOUT THAT", "How about that.", "vo/npc/female01/answer25.wav")
Schema.voices.Add("CitizenFemale", "MORE INFORMATION", "That's more information than I require.", "vo/npc/female01/answer26.wav")
Schema.voices.Add("CitizenFemale", "WANNA BET", "Wanna bet?", "vo/npc/female01/answer27.wav")
Schema.voices.Add("CitizenFemale", "WISH I HAD A DIME", "I wish I had a dime for every time somebody said that.", "vo/npc/female01/answer28.wav")
Schema.voices.Add("CitizenFemale", "WHAT AM I SUPPOSED TO DO", "What am I supposed to do about it?", "vo/npc/female01/answer29.wav")
Schema.voices.Add("CitizenFemale", "TALKING TO ME", "You talking to me?", "vo/npc/female01/answer30.wav")
Schema.voices.Add("CitizenFemale", "NIP THAT TALK", "You should nip that kind of talk in the bud.", "vo/npc/female01/answer31.wav")
Schema.voices.Add("CitizenFemale", "RIGHT ON", "Right on.", "vo/npc/female01/answer32.wav")
Schema.voices.Add("CitizenFemale", "NO ARGUMENT", "No argument there.", "vo/npc/female01/answer33.wav")
Schema.voices.Add("CitizenFemale", "DON'T FORGET HAWAII", "Don't forget Hawaii", "vo/npc/female01/answer34.wav")
Schema.voices.Add("CitizenFemale", "DON'T LET IT GET TO YOU", "Try not to let it get to you.", "vo/npc/female01/answer35.wav")
Schema.voices.Add("CitizenFemale", "FIRST TIME", "Wouldn't be the first time.", "vo/npc/female01/answer36.wav")
Schema.voices.Add("CitizenFemale", "SURE ABOUT THAT", "You sure about that?", "vo/npc/female01/answer37.wav")
Schema.voices.Add("CitizenFemale", "LEAVE IT", "Leave it alone.", "vo/npc/female01/answer38.wav")
Schema.voices.Add("CitizenFemale", "ENOUGH OUTTA YOU", "That's enough outta you.", "vo/npc/female01/answer39.wav")
Schema.voices.Add("CitizenFemale", "FIRST TIME FOR EVERYTHING", "There's a first time for everything.", "vo/npc/female01/answer40.wav")
Schema.voices.Add("CitizenFemale", "BEHIND YOU", "Behind you!", "vo/npc/female01/behindyou01.wav")
Schema.voices.Add("CitizenFemale", "BEHIND YOU2", "Behind you!", "vo/npc/female01/behindyou02.wav")
Schema.voices.Add("CitizenFemale", "IM BUSY", "Can't you see I'm busy?", "vo/npc/female01/busy02.wav")
Schema.voices.Add("CitizenFemale", "SUPPLIES", "Hey down there! Supplies!", "vo/npc/female01/cit_dropper01.wav")
Schema.voices.Add("CitizenFemale", "LOOK OUT BELOW", "Look out below!", "vo/npc/female01/cit_dropper04.wav")
Schema.voices.Add("CitizenFemale", "CIVIL PROTECTION", "Civil Protection!", "vo/npc/female01/civilprotection01.wav")
Schema.voices.Add("CitizenFemale", "CIVIL PROTECTION2", "Civil Protection!", "vo/npc/female01/civilprotection02.wav")
Schema.voices.Add("CitizenFemale", "COMBINE", "Combine!", "vo/npc/female01/combine01.wav")
Schema.voices.Add("CitizenFemale", "COMBINE2", "Combine!", "vo/npc/female01/combine02.wav")
Schema.voices.Add("CitizenFemale", "RELOADING", "Cover me while I reload!", "vo/npc/female01/coverwhilereload01.wav")
Schema.voices.Add("CitizenFemale", "RELOADING2", "Cover me while I reload!", "vo/npc/female01/coverwhilereload02.wav")
Schema.voices.Add("CitizenFemale", "CPS", "CPs!", "vo/npc/female01/cps01.wav")
Schema.voices.Add("CitizenFemale", "CPS2", "CPs!", "vo/npc/female01/cps02.wav")
Schema.voices.Add("CitizenFemale", "DOING SOMETHING", "Shouldn't we be doing something?", "vo/npc/female01/doingsomething.wav")
Schema.voices.Add("CitizenFemale", "EXCUSE ME", "Excuse me.", "vo/npc/female01/excuseme01.wav")
Schema.voices.Add("CitizenFemale", "EXCUSE ME2", "Excuse me.", "vo/npc/female01/excuseme02.wav")
Schema.voices.Add("CitizenFemale", "FANTASTIC", "Fantastic.", "vo/npc/female01/fantastic01.wav")
Schema.voices.Add("CitizenFemale", "FANTASTIC2", "Fantastic.", "vo/npc/female01/fantastic02.wav")
Schema.voices.Add("CitizenFemale", "FINALLY", "Finally.", "vo/npc/female01/finally.wav")
Schema.voices.Add("CitizenFemale", "GET DOWN", "Get down!", "vo/npc/female01/getdown02.wav")
Schema.voices.Add("CitizenFemale", "GET GOING SOON", "Are we gonna get going soon?", "vo/npc/female01/getgoingsoon.wav")
Schema.voices.Add("CitizenFemale", "GET THE HELL OUTTA HERE", "Get the hell outta here!", "vo/npc/female01/gethellout.wav")
Schema.voices.Add("CitizenFemale", "GOOD GOD", "Good god!", "vo/npc/female01/goodgod.wav")
Schema.voices.Add("CitizenFemale", "NOW WHAT", "Now what?", "vo/npc/female01/gordead_ans01.wav")
Schema.voices.Add("CitizenFemale", "GOING SOWELL", "And things were going so well.", "vo/npc/female01/gordead_ans02.wav")
Schema.voices.Add("CitizenFemale", "DON'T TELL ME", "Don't tell me.", "vo/npc/female01/gordead_ans03.wav")
Schema.voices.Add("CitizenFemale", "OH GOD", "Oh God.", "vo/npc/female01/gordead_ans04.wav")
Schema.voices.Add("CitizenFemale", "OH NO", "Oh no.", "vo/npc/female01/gordead_ans05.wav")
Schema.voices.Add("CitizenFemale", "PLEASE NO", "Please, no.", "vo/npc/female01/gordead_ans06.wav")
Schema.voices.Add("CitizenFemale", "IF YOU DARE SAY", "If you dare say 'That's gotta hurt', I'll kill you.", "vo/npc/female01/gordead_ans07.wav")
Schema.voices.Add("CitizenFemale", "SHOULD WE BURY HIM", "Should we bury him here?", "vo/npc/female01/gordead_ans08.wav")
Schema.voices.Add("CitizenFemale", "SPREAD THE WORD", "Spread the word.", "vo/npc/female01/gordead_ans10.wav")
Schema.voices.Add("CitizenFemale", "WHATS THE USE", "What's the use?", "vo/npc/female01/gordead_ans11.wav")
Schema.voices.Add("CitizenFemale", "WHATS THE POINT", "What's the point?", "vo/npc/female01/gordead_ans12.wav")
Schema.voices.Add("CitizenFemale", "WHY GO ON", "Why go on?", "vo/npc/female01/gordead_ans13.wav")
Schema.voices.Add("CitizenFemale", "WERE DONE FOR", "We're done for.", "vo/npc/female01/gordead_ans14.wav")
Schema.voices.Add("CitizenFemale", "NOW WHAT2", "Well, now what?", "vo/npc/female01/gordead_ans15.wav")
Schema.voices.Add("CitizenFemale", "DONE THIS BEFORE", "He's done this before, he'll be ok.", "vo/npc/female01/gordead_ans18.wav")
Schema.voices.Add("CitizenFemale", "IM GONNA BE SICK", "I'm gonna be sick.", "vo/npc/female01/gordead_ans19.wav")
Schema.voices.Add("CitizenFemale", "HES DEAD", "He's dead.", "vo/npc/female01/gordead_ques01.wav")
Schema.voices.Add("CitizenFemale", "WAY TO GO", "What a way to go.", "vo/npc/female01/gordead_ques02.wav")
Schema.voices.Add("CitizenFemale", "THIS CAN'T BE", "This can't be.", "vo/npc/female01/gordead_ques06.wav")
Schema.voices.Add("CitizenFemale", "HES DEAD2", "Look, he's dead!", "vo/npc/female01/gordead_ques07.wav")
Schema.voices.Add("CitizenFemale", "THIS IS BAD", "This is bad.", "vo/npc/female01/gordead_ques10.wav")
Schema.voices.Add("CitizenFemale", "NOT SUPPOSED TO END", "It's not supposed to end like this!", "vo/npc/female01/gordead_ques14.wav")
Schema.voices.Add("CitizenFemale", "WHAT NOW", "What now?", "vo/npc/female01/gordead_ques16.wav")
Schema.voices.Add("CitizenFemale", "GOT ONE", "Got one!", "vo/npc/female01/gotone01.wav")
Schema.voices.Add("CitizenFemale", "GOT ONE2", "I got one!", "vo/npc/female01/gotone02.wav")
Schema.voices.Add("CitizenFemale", "RELOADING3", "Gotta reload.", "vo/npc/female01/gottareload01.wav")
Schema.voices.Add("CitizenFemale", "GUNSHIP3", "Gunship!", "vo/npc/female01/gunship02.wav")
Schema.voices.Add("CitizenFemale", "HEADCRABS", "Headcrabs!", "vo/npc/female01/headcrabs01.wav")
Schema.voices.Add("CitizenFemale", "HEADCRABS2", "Headcrabs!", "vo/npc/female01/headcrabs02.wav")
Schema.voices.Add("CitizenFemale", "HEADSUP", "Heads up!", "vo/npc/female01/headsup01.wav")
Schema.voices.Add("CitizenFemale", "HEADSUP2", "Heads up!", "vo/npc/female01/headsup02.wav")
Schema.voices.Add("CitizenFemale", "MEDKIT", "Take this medkit.", "vo/npc/female01/health01.wav")
Schema.voices.Add("CitizenFemale", "MEDKIT2", "Take this medkit.", "vo/npc/female01/health02.wav")
Schema.voices.Add("CitizenFemale", "MEDKIT3", "Take this medkit.", "vo/npc/female01/health03.wav")
Schema.voices.Add("CitizenFemale", "MEDKIT4", "Here, have a medkit.", "vo/npc/female01/health04.wav")
Schema.voices.Add("CitizenFemale", "MEDKIT5", "Here, patch yourself up.", "vo/npc/female01/health05.wav")
Schema.voices.Add("CitizenFemale", "HELP", "Help!", "vo/npc/female01/help01.wav")
Schema.voices.Add("CitizenFemale", "HERE COME THE HACKS", "Here come the hacks!", "vo/npc/female01/herecomehacks01.wav")
Schema.voices.Add("CitizenFemale", "HERE COME THE HACKS2", "Here come the hacks!", "vo/npc/female01/herecomehacks02.wav")
Schema.voices.Add("CitizenFemale", "HERE THEY COME", "Here they come!", "vo/npc/female01/heretheycome01.wav")
Schema.voices.Add("CitizenFemale", "HI", "Hi.", "vo/npc/female01/hi01.wav")
Schema.voices.Add("CitizenFemale", "HI2", "Hi.", "vo/npc/female01/hi02.wav")
Schema.voices.Add("CitizenFemale", "HIT IN THE GUT", "Hit in the gut.", "vo/npc/female01/hitingut01.wav")
Schema.voices.Add("CitizenFemale", "HIT IN THE GUT2", "Hit in the gut.", "vo/npc/female01/hitingut02.wav")
Schema.voices.Add("CitizenFemale", "HOLD DOWN THIS SPOT", "I'm gonna stay and hold down this spot.", "vo/npc/female01/holddownspot01.wav")
Schema.voices.Add("CitizenFemale", "HOLD DOWN THIS SPOT2", "I'm gonna stay and hold down this spot.", "vo/npc/female01/holddownspot02.wav")
Schema.voices.Add("CitizenFemale", "ILL STAY HERE", "I'll stay here.", "vo/npc/female01/illstayhere01.wav")
Schema.voices.Add("CitizenFemale", "IM HURT", "I'm hurt.", "vo/npc/female01/imhurt01.wav")
Schema.voices.Add("CitizenFemale", "IM HURT2", "I'm hurt.", "vo/npc/female01/imhurt02.wav")
Schema.voices.Add("CitizenFemale", "IM STICKING HERE", "I'm sticking here.", "vo/npc/female01/imstickinghere01.wav")
Schema.voices.Add("CitizenFemale", "INCOMING2", "Incoming!", "vo/npc/female01/incoming02.wav")
Schema.voices.Add("CitizenFemale", "ITS A MANHACK", "It's a manhack!", "vo/npc/female01/itsamanhack01.wav")
Schema.voices.Add("CitizenFemale", "ITS A MANKACK2", "It's a manhack!", "vo/npc/female01/itsamanhack02.wav")
Schema.voices.Add("CitizenFemale", "LEAD THE WAY", "You lead the way!", "vo/npc/female01/leadtheway01.wav")
Schema.voices.Add("CitizenFemale", "LEAD THE WAY2", "Lead the way!", "vo/npc/female01/leadtheway02.wav")
Schema.voices.Add("CitizenFemale", "LETS GO", "Let's go!", "vo/npc/female01/letsgo01.wav")
Schema.voices.Add("CitizenFemale", "LETS GO2", "Let's go!", "vo/npc/female01/letsgo02.wav")
Schema.voices.Add("CitizenFemale", "LIKE THAT", "Like that?!", "vo/npc/female01/likethat.wav")
Schema.voices.Add("CitizenFemale", "CORNER", "I've got my little corner and I'm sticking to it.", "vo/npc/female01/littlecorner01.wav")
Schema.voices.Add("CitizenFemale", "GROAN", "*Groan.*", "vo/npc/female01/moan01.wav")
Schema.voices.Add("CitizenFemale", "GROAN2", "*Groan.*", "vo/npc/female01/moan02.wav")
Schema.voices.Add("CitizenFemale", "GROAN3", "*Groan.*", "vo/npc/female01/moan03.wav")
Schema.voices.Add("CitizenFemale", "GROAN4", "*Groan.*", "vo/npc/female01/moan04.wav")
Schema.voices.Add("CitizenFemale", "GROAN5", "*Groan.*", "vo/npc/female01/moan05.wav")
Schema.voices.Add("CitizenFemale", "MY ARM", "My arm.", "vo/npc/female01/myarm01.wav")
Schema.voices.Add("CitizenFemale", "MY ARM2", "My arm.", "vo/npc/female01/myarm02.wav")
Schema.voices.Add("CitizenFemale", "MY GUT", "My gut.", "vo/npc/female01/mygut02.wav")
Schema.voices.Add("CitizenFemale", "MY LEG", "My leg.", "vo/npc/female01/myleg01.wav")
Schema.voices.Add("CitizenFemale", "MY LEG2", "My leg.", "vo/npc/female01/myleg02.wav")
Schema.voices.Add("CitizenFemale", "NICE", "Nice.", "vo/npc/female01/nice.wav")
Schema.voices.Add("CitizenFemale", "OH NO2", "Oh no.", "vo/npc/female01/ohno.wav")
Schema.voices.Add("CitizenFemale", "OK", "Ok.", "vo/npc/female01/ok01.wav")
Schema.voices.Add("CitizenFemale", "OK2", "Ok.", "vo/npc/female01/ok02.wav")
Schema.voices.Add("CitizenFemale", "OK IM READY", "Ok, I'm ready.", "vo/npc/female01/okimready01.wav")
Schema.voices.Add("CitizenFemale", "OK IM READY2", "Ok, I'm ready.", "vo/npc/female01/okimready02.wav")
Schema.voices.Add("CitizenFemale", "OK IM READY3", "Ok, I'm ready!", "vo/npc/female01/okimready03.wav")
Schema.voices.Add("CitizenFemale", "ONE FOR ME", "One for me and one for me.", "vo/npc/female01/oneforme.wav")
Schema.voices.Add("CitizenFemale", "OUT OF YOUR WAY", "Let me get out of your way.", "vo/npc/female01/outofyourway02.wav")
Schema.voices.Add("CitizenFemale", "HEY OVER HERE", "Hey over here!", "vo/npc/female01/overhere01.wav")
Schema.voices.Add("CitizenFemale", "OVER THERE", "Over there!", "vo/npc/female01/overthere01.wav")
Schema.voices.Add("CitizenFemale", "OVER THERE2", "Over there!", "vo/npc/female01/overthere02.wav")
Schema.voices.Add("CitizenFemale", "OW", "Ow!", "vo/npc/female01/ow01.wav")
Schema.voices.Add("CitizenFemale", "OW2", "Ow!", "vo/npc/female01/ow02.wav")
Schema.voices.Add("CitizenFemale", "PARDON ME", "Pardon me.", "vo/npc/female01/pardonme01.wav")
Schema.voices.Add("CitizenFemale", "PARDON ME2", "Pardon me.", "vo/npc/female01/pardonme02.wav")
Schema.voices.Add("CitizenFemale", "EVER GONNA END", "I don't think this war is ever gonna end.", "vo/npc/female01/question01.wav")
Schema.voices.Add("CitizenFemale", "INSURANCE", "To think, all I used to want to do was sell insurance.", "vo/npc/female01/question02.wav")
Schema.voices.Add("CitizenFemale", "DON'T DREAM", "I don't dream anymore.", "vo/npc/female01/question03.wav")
Schema.voices.Add("CitizenFemale", "WHEN THIS IS OVER", "When this is all over I'm...aw, who am I kidding?", "vo/npc/female01/question04.wav")
Schema.voices.Add("CitizenFemale", "DEJAVU", "Woah, Deja vu.", "vo/npc/female01/question05.wav")
Schema.voices.Add("CitizenFemale", "CHEESE", "Sometimes, I dream about cheese.", "vo/npc/female01/question06.wav")
Schema.voices.Add("CitizenFemale", "FREEDOM", "You semm that? It's freedom!", "vo/npc/female01/question07.wav")
Schema.voices.Add("CitizenFemale", "EAT A HORSE", "I could eat a horse, hooves and all.", "vo/npc/female01/question09.wav")
Schema.voices.Add("CitizenFemale", "CAN'T BELIEVE THIS DAY", "I can't believe this day has finally come!", "vo/npc/female01/question10.wav")
Schema.voices.Add("CitizenFemale", "NOT PART OF PLAN", "I'm pretty sure this isn't part of the plan.", "vo/npc/female01/question11.wav")
Schema.voices.Add("CitizenFemale", "WORSE NOT BETTER", "Looks to me things are getting worse, not better.", "vo/npc/female01/question12.wav")
Schema.voices.Add("CitizenFemale", "LIVE MY LIFE ALL OVER", "If I could live my life all over again.", "vo/npc/female01/question13.wav")
Schema.voices.Add("CitizenFemale", "WHAT THAT REMINDS ME", "I'm not even gonna tell you what that reminds me of.", "vo/npc/female01/question14.wav")
Schema.voices.Add("CitizenFemale", "STALKER OUT OF ME", "They're never gonna make a stalker out of me.", "vo/npc/female01/question15.wav")
Schema.voices.Add("CitizenFemale", "CHANGE IS IN THE AIR", "Finally, change is in the air!", "vo/npc/female01/question16.wav")
Schema.voices.Add("CitizenFemale", "YOU FEEL IT", "You feel it? I feel it!", "vo/npc/female01/question17.wav")
Schema.voices.Add("CitizenFemale", "DON'T FEEL ANYTHING", "I don't feel anything anymore.", "vo/npc/female01/question18.wav")
Schema.voices.Add("CitizenFemale", "SHOWER", "I can't remember the last time I had a shower.", "vo/npc/female01/question19.wav")
Schema.voices.Add("CitizenFemale", "BAD MEMORY", "Some day, this will all be a bad memory.", "vo/npc/female01/question20.wav")
Schema.voices.Add("CitizenFemale", "BETTING", "I'm not a betting man, but the odds are not good.", "vo/npc/female01/question21.wav")
Schema.voices.Add("CitizenFemale", "CARE WHAT I THINK", "Doesn't anyone care what I think?", "vo/npc/female01/question22.wav")
Schema.voices.Add("CitizenFemale", "TUNE", "I can't get this tune out of my head. *Whistling.*", "vo/npc/female01/question23.wav")
Schema.voices.Add("CitizenFemale", "ONE OF THOSE DAYS", "I just knew it was gonna be one of those days.", "vo/npc/female01/question25.wav")
Schema.voices.Add("CitizenFemale", "BULLSHIT", "This is bullshit.", "vo/npc/female01/question26.wav")
Schema.voices.Add("CitizenFemale", "ATE SOMETHING BAD", "I think I ate something bad.", "vo/npc/female01/question27.wav")
Schema.voices.Add("CitizenFemale", "HUNGRY", "God, I'm hungry.", "vo/npc/female01/question28.wav")
Schema.voices.Add("CitizenFemale", "IM GONNA MATE", "When this is all over, I'm gonna mate.", "vo/npc/female01/question29.wav")
Schema.voices.Add("CitizenFemale", "NO KIDS", "I'm glad there's no kids around to see this.", "vo/npc/female01/question30.wav")
Schema.voices.Add("CitizenFemale", "READY WHEN YOU ARE", "Ready when you are!", "vo/npc/female01/readywhenyouare01.wav")
Schema.voices.Add("CitizenFemale", "READY WHEN YOU ARE2", "Ready when you are!", "vo/npc/female01/readywhenyouare02.wav")
Schema.voices.Add("CitizenFemale", "RUN FOR YOUR LIFE", "Run for your life!", "vo/npc/female01/runforyourlife01.wav")
Schema.voices.Add("CitizenFemale", "RUN FOR YOUR LIFE2", "Run for your life!", "vo/npc/female01/runforyourlife02.wav")
Schema.voices.Add("CitizenFemale", "RUN FOR YOUR LIFE3", "Run for your life!", "vo/npc/female01/runforyourlife03.wav")
Schema.voices.Add("CitizenFemale", "SCANNERS", "Scanners!", "vo/npc/female01/scanners01.wav")
Schema.voices.Add("CitizenFemale", "SCANNERS2", "Scanners!", "vo/npc/female01/scanners02.wav")
Schema.voices.Add("CitizenFemale", "SORRY", "Sorry.", "vo/npc/female01/sorry01.wav")
Schema.voices.Add("CitizenFemale", "SORRY2", "Sorry.", "vo/npc/female01/sorry02.wav")
Schema.voices.Add("CitizenFemale", "SORRY3", "Sorry.", "vo/npc/female01/sorry03.wav")
Schema.voices.Add("CitizenFemale", "WHAT EVER YOU SAY", "Whatever you say.", "vo/npc/female01/squad_affirm03.wav")
Schema.voices.Add("CitizenFemale", "OK IM GOING", "Ok, I'm going.", "vo/npc/female01/squad_affirm04.wav")
Schema.voices.Add("CitizenFemale", "HERE GOES", "Here goes.", "vo/npc/female01/squad_affirm05.wav")
Schema.voices.Add("CitizenFemale", "HERE GOES NOTHING", "Here goes nothing.", "vo/npc/female01/squad_affirm06.wav")
Schema.voices.Add("CitizenFemale", "HERE WE COME", "Here we come!", "vo/npc/female01/squad_approach02.wav")
Schema.voices.Add("CitizenFemale", "ON OUR WAY", "On our way!", "vo/npc/female01/squad_approach03.wav")
Schema.voices.Add("CitizenFemale", "COMING", "Coming!", "vo/npc/female01/squad_approach04.wav")
Schema.voices.Add("CitizenFemale", "THIS WAY GANG", "This way gang!", "vo/npc/female01/squad_away01.wav")
Schema.voices.Add("CitizenFemale", "OVER HERE", "Over here!", "vo/npc/female01/squad_away02.wav")
Schema.voices.Add("CitizenFemale", "FOLLOW ME", "Follow me!", "vo/npc/female01/squad_away03.wav")
Schema.voices.Add("CitizenFemale", "COME ON EVERY BODY", "Come on everybody!", "vo/npc/female01/squad_follow02.wav")
Schema.voices.Add("CitizenFemale", "LETS GET MOVING", "Let's get moving.", "vo/npc/female01/squad_follow03.wav")
Schema.voices.Add("CitizenFemale", "WAIT FOR US", "Wait for us!", "vo/npc/female01/squad_reinforce_group04.wav")
Schema.voices.Add("CitizenFemale", "WAIT FOR ME", "Wait for me!", "vo/npc/female01/squad_reinforce_single04.wav")
Schema.voices.Add("CitizenFemale", "GASP", "*Gasp.*", "vo/npc/female01/startle01.wav")
Schema.voices.Add("CitizenFemale", "GASP2", "*Gasp.*", "vo/npc/female01/startle02.wav")
Schema.voices.Add("CitizenFemale", "STRIDER", "Strider!", "vo/npc/female01/strider.wav")
Schema.voices.Add("CitizenFemale", "RUN", "Run!", "vo/npc/female01/strider_run.wav")
Schema.voices.Add("CitizenFemale", "TAKE COVER", "Take cover!", "vo/npc/female01/takecover02.wav")
Schema.voices.Add("CitizenFemale", "THIS WILL DO NICELY", "This will do nicely.", "vo/npc/female01/thislldonicely01.wav")
Schema.voices.Add("CitizenFemale", "UH OH", "Uh oh.", "vo/npc/female01/uhoh.wav")
Schema.voices.Add("CitizenFemale", "UP THERE", "Up there!", "vo/npc/female01/upthere01.wav")
Schema.voices.Add("CitizenFemale", "UP THERE2", "Up there!", "vo/npc/female01/upthere02.wav")
Schema.voices.Add("CitizenFemale", "MUMBOJUMBO", "Enough of your mumbo jumbo.", "vo/npc/female01/vanswer01.wav")
Schema.voices.Add("CitizenFemale", "DAMN VORTS", "Damn vorts.", "vo/npc/female01/vanswer02.wav")
Schema.voices.Add("CitizenFemale", "NOT SURE HOW TO TAKE THAT", "I'm not sure how to take that.", "vo/npc/female01/vanswer03.wav")
Schema.voices.Add("CitizenFemale", "TAKE THAT PERSONALLY", "Should I take that personally?", "vo/npc/female01/vanswer04.wav")
Schema.voices.Add("CitizenFemale", "SPEAK ENGLISH", "Speak English.", "vo/npc/female01/vanswer05.wav")
Schema.voices.Add("CitizenFemale", "GOT FROM ME", "You got that from me.", "vo/npc/female01/vanswer06.wav")
Schema.voices.Add("CitizenFemale", "WE PUT UP WITH YOU", "That's why we put up with you.", "vo/npc/female01/vanswer07.wav")
Schema.voices.Add("CitizenFemale", "PUT IT BETTER MYSELF", "Couldn't have put it better myself.", "vo/npc/female01/vanswer08.wav")
Schema.voices.Add("CitizenFemale", "ALMOST MADE SENSE", "That... almost made sense.", "vo/npc/female01/vanswer09.wav")
Schema.voices.Add("CitizenFemale", "ALMOST UNDERSTOOD", "Something must be wrong with me, I almost understood that.", "vo/npc/female01/vanswer10.wav")
Schema.voices.Add("CitizenFemale", "GETTING USED TO VORTS", "I guess I'm getting used to you vorts.", "vo/npc/female01/vanswer11.wav")
Schema.voices.Add("CitizenFemale", "VORT PHILOSOPHY", "None of your vort philosoply.", "vo/npc/female01/vanswer12.wav")
Schema.voices.Add("CitizenFemale", "KILLING ME", "Stop, you're killing me.", "vo/npc/female01/vanswer13.wav")
Schema.voices.Add("CitizenFemale", "DESERVE THIS", "What did I do to deserve this?", "vo/npc/female01/vanswer14.wav")
Schema.voices.Add("CitizenFemale", "STOP LOOKING", "Stop looking at me like that.", "vo/npc/female01/vquestion01.wav")
Schema.voices.Add("CitizenFemale", "NEVER GET USED TO", "Some things I just never get used to.", "vo/npc/female01/vquestion02.wav")
Schema.voices.Add("CitizenFemale", "HOW YOU THINGS", "I don't know how you things have survived as long as you have.", "vo/npc/female01/vquestion03.wav")
Schema.voices.Add("CitizenFemale", "HOW I ENDED UP", "Sometimes I wonder how I ended up with you.", "vo/npc/female01/vquestion04.wav")
Schema.voices.Add("CitizenFemale", "YOURE ALRIGHT VORTY", "You're all right vorty.", "vo/npc/female01/vquestion05.wav")
Schema.voices.Add("CitizenFemale", "VORTS ARENT HALF BAD", "You vorts aren't half bad.", "vo/npc/female01/vquestion06.wav")
Schema.voices.Add("CitizenFemale", "PALS WITH A VORT", "If anyone would have told me I'd be pals with a vortigaunt...", "vo/npc/female01/vquestion07.wav")
Schema.voices.Add("CitizenFemale", "WAITING FOR SOMEBODY", "You waiting for somebody?", "vo/npc/female01/waitingsomebody.wav")
Schema.voices.Add("CitizenFemale", "WATCH OUT", "Watch out!", "vo/npc/female01/watchout.wav")
Schema.voices.Add("CitizenFemale", "WHATCH WHAT YOURE DOING", "Watch what you're doing!", "vo/npc/female01/watchwhat.wav")
Schema.voices.Add("CitizenFemale", "WE TRUSTED YOU", "We trusted you!", "vo/npc/female01/wetrustedyou01.wav")
Schema.voices.Add("CitizenFemale", "WE TRUSTED YOU2", "We trusted you!", "vo/npc/female01/wetrustedyou02.wav")
Schema.voices.Add("CitizenFemale", "WHOOPS", "Whoops.", "vo/npc/female01/whoops01.wav")
Schema.voices.Add("CitizenFemale", "YEAH", "Yeah.", "vo/npc/female01/yeah02.wav")
Schema.voices.Add("CitizenFemale", "BETTERR ELOAD", "You better reload.", "vo/npc/female01/youdbetterreload01.wav")
Schema.voices.Add("CitizenFemale", "YOU GOT IT", "You got it.", "vo/npc/female01/yougotit02.wav")
Schema.voices.Add("CitizenFemale", "ZOMBIES", "Zombies!", "vo/npc/female01/zombies01.wav")
Schema.voices.Add("CitizenFemale", "ZOMBIES2", "Zombies!", "vo/npc/female01/zombies02.wav")

-- streetwar

Schema.voices.Add("CitizenMale", "HOPPERS", "Watch out for the hoppers! They're everywhere!", "vo/streetwar/barricade/male01/c17_05_hoppers.wav")
Schema.voices.Add("CitizenMale", "LET US THROUGH", "Let us through!", "vo/streetwar/barricade/male01/c17_05_letusthru.wav")
Schema.voices.Add("CitizenMale", "OPEN THE GATE", "Open the gate!", "vo/streetwar/barricade/male01/c17_05_opengate.wav")
Schema.voices.Add("CitizenMale", "LET US OUT", "Hey! Let us out of here!", "vo/streetwar/nexus/male01/c17_10_letusout.wav")
Schema.voices.Add("CitizenMale", "HORSE", "Head for the horse!", "vo/streetwar/rubble/male01/d3_c17_13_horse01.wav")
Schema.voices.Add("CitizenMale", "HORSE2", "We have to get to the horse!", "vo/streetwar/rubble/male01/d3_c17_13_horse02.wav")
Schema.voices.Add("CitizenMale", "HELP2", "Help!", "vo/streetwar/sniper/male01/c17_09_help01.wav")
Schema.voices.Add("CitizenMale", "HELP ME", "Help me!", "vo/streetwar/sniper/male01/c17_09_help02.wav")
Schema.voices.Add("CitizenMale", "SOME BODY UP THERE", "Is somebody up there?", "vo/streetwar/sniper/male01/c17_09_help03.wav")
Schema.voices.Add("CitizenMale", "ALMOST DONE", "If you can hold them off, I'm almost done here!", "vo/streetwar/tunnel/male01/c17_06_det02.wav")
Schema.voices.Add("CitizenMale", "LAST CHARGE", "Ok, last charge!", "vo/streetwar/tunnel/male01/c17_06_det03.wav")
Schema.voices.Add("CitizenMale", "ITS GONNA BLOW", "Stand back! It's gonna blow!", "vo/streetwar/tunnel/male01/c17_06_det04.wav")
Schema.voices.Add("CitizenMale", "OPEN THE DOOR", "Hey, It's me. Open the door.", "vo/streetwar/tunnel/male01/c17_06_password01.wav")
Schema.voices.Add("CitizenMale", "PASSWORD", "What's the password?", "vo/streetwar/tunnel/male01/c17_06_password02.wav")
Schema.voices.Add("CitizenMale", "PASSWORD2", "Password!", "vo/streetwar/tunnel/male01/c17_06_password03.wav")
Schema.voices.Add("CitizenMale", "COME ON IN", "Come on in.", "vo/streetwar/tunnel/male01/c17_06_password04.wav")
Schema.voices.Add("CitizenMale", "COME ACROSS", "Ok, come across.", "vo/streetwar/tunnel/male01/c17_06_plank01.wav")
Schema.voices.Add("CitizenMale", "COME ACROSS2", "I've got to stay here in case anyone else needs to get across.", "vo/streetwar/tunnel/male01/c17_06_plank02.wav")
Schema.voices.Add("CitizenMale", "MADE IT THROUGH", "I see you made it through okay. Figured you would.", "vo/streetwar/tunnel/male01/d3_c17_06_post_det04.wav")

Schema.voices.Add("CitizenFemale", "HOPPERS", "Watch out for the hoppers! They're everywhere!", "vo/streetwar/barricade/female01/c17_05_hoppers.wav")
Schema.voices.Add("CitizenFemale", "LETUSTHROUGH", "Let us through!", "vo/streetwar/barricade/female01/c17_05_letusthru.wav")
Schema.voices.Add("CitizenFemale", "OPENTHEGATE", "Open the gate!", "vo/streetwar/barricade/female01/c17_05_opengate.wav")
Schema.voices.Add("CitizenFemale", "LETUSOUT", "Hey! Let us out of here!", "vo/streetwar/nexus/female01/c17_10_letusout.wav")
Schema.voices.Add("CitizenFemale", "HORSE", "Head for the horse!", "vo/streetwar/rubble/female01/d3_c17_13_horse01.wav")
Schema.voices.Add("CitizenFemale", "HORSE2", "We have to get to the horse!", "vo/streetwar/rubble/female01/d3_c17_13_horse02.wav")
Schema.voices.Add("CitizenFemale", "ALMOSTDONE", "If you can hold them off, I'm almost done here!", "vo/streetwar/tunnel/female01/c17_06_det02.wav")
Schema.voices.Add("CitizenFemale", "LASTCHARGE", "Ok, last charge!", "vo/streetwar/tunnel/female01/c17_06_det03.wav")
Schema.voices.Add("CitizenFemale", "ITSGONNABLOW", "Stand back! It's gonna blow!", "vo/streetwar/tunnel/female01/c17_06_det04.wav")
Schema.voices.Add("CitizenFemale", "OPENTHEDOOR", "Hey, It's me. Open the door.", "vo/streetwar/tunnel/female01/c17_06_password01.wav")
Schema.voices.Add("CitizenFemale", "PASSWORD", "What's the password?", "vo/streetwar/tunnel/female01/c17_06_password02.wav")
Schema.voices.Add("CitizenFemale", "COMEONIN", "Come on in.", "vo/streetwar/tunnel/female01/c17_06_password04.wav")
Schema.voices.Add("CitizenFemale", "COMEACROSS", "Ok, come across.", "vo/streetwar/tunnel/female01/c17_06_plank01.wav")
Schema.voices.Add("CitizenFemale", "COMEACROSS2", "I've got to stay here in case anyone else needs to get across.", "vo/streetwar/tunnel/female01/c17_06_plank02.wav")
Schema.voices.Add("CitizenFemale", "MADEITTHROUGH", "I see you made it through okay. Figured you would.", "vo/streetwar/tunnel/female01/d3_c17_06_post_det04.wav")

-- trainyard

Schema.voices.Add("CitizenMale", "BASE", "I wouldn't say that too loud. This is his base of operations.", "vo/trainyard/cit_tooloud.wav")
Schema.voices.Add("CitizenMale", "GET IN HERE3", "Get in here, quick!", "vo/trainyard/cit_blocker_getin.wav")
Schema.voices.Add("CitizenMale", "GET GOING5", "Get going!", "vo/trainyard/cit_blocker_go01.wav")
Schema.voices.Add("CitizenMale", "GO ON3", "Go on!", "vo/trainyard/cit_blocker_go02.wav")
Schema.voices.Add("CitizenMale", "GET GOING6", "Get going!", "vo/trainyard/cit_blocker_go03.wav")
Schema.voices.Add("CitizenMale", "ILL HOLD THEM", "Go on, I'll hold them!", "vo/trainyard/cit_blocker_holdem.wav")
Schema.voices.Add("CitizenMale", "HEAD FOR ROOF", "Keep going, head for the roof!", "vo/trainyard/cit_blocker_roof.wav")
Schema.voices.Add("CitizenMale", "YOU KNOCKING", "Was that you knocking? I didn't even know we still had a door.", "vo/trainyard/cit_drunk.wav")
Schema.voices.Add("CitizenMale", "COUPON", "This must be a mistake. I got a standard relocation coupon just like everybody else!", "vo/trainyard/cit_cell_coupon.wav")
Schema.voices.Add("CitizenMale", "HEY YOU", "Psst! Hey you! In here!", "vo/trainyard/cit_hall_psst.wav")
Schema.voices.Add("CitizenMale", "HEAD FOR ROOF2", "Head for the roof! There's no time to loose!", "vo/trainyard/cit_hall_roof.wav")
Schema.voices.Add("CitizenMale", "ALL I HAVE LEFT", "But this stuff, it's all I have left.", "vo/trainyard/cit_lug_allihave.wav")
Schema.voices.Add("CitizenMale", "IM MOVING JEEZ", "Alright I'm moving, Jeez.", "vo/trainyard/cit_lug_allright.wav")
Schema.voices.Add("CitizenMale", "NERVE", "I'm working up the nerve to go on.", "vo/trainyard/cit_nerve.wav")
Schema.voices.Add("CitizenMale", "FIND ONE", "Don't worry, they'll find one.", "vo/trainyard/cit_raid_findone.wav")
Schema.voices.Add("CitizenMale", "NO REASON", "They have no reason to come to our place.", "vo/trainyard/cit_raid_reason.wav")
Schema.voices.Add("CitizenMale", "THEN THE WHOLE BLOCK", "This is how it always starts. First a building, then the whole block.", "vo/trainyard/cit_raid_start.wav")
Schema.voices.Add("CitizenMale", "DON'T LIVE THERE", "Just be glad you don't live there.", "vo/trainyard/cit_raid_use01.wav")
Schema.voices.Add("CitizenMale", "PLACE TO STAY", "If you're looking for a place to stay, you better keep going.", "vo/trainyard/cit_raid_use02.wav")
Schema.voices.Add("CitizenMale", "SUIT CASE", "	I see they took your suitcase too! They can't get away with this much longer.", "vo/trainyard/cit_tookcase.wav")
Schema.voices.Add("CitizenMale", "END OF THE LINE", "Well, end of the line.", "vo/trainyard/cit_train_endline.wav")
Schema.voices.Add("CitizenMale", "DIDNT SEE YOU", "I didn't see you get on.", "vo/trainyard/cit_train_geton.wav")
Schema.voices.Add("CitizenMale", "RELOCATED", "No matter how many times I've been relocated, I never get used to it.", "vo/trainyard/cit_train_reloc.wav")
Schema.voices.Add("CitizenMale", "WATER", "Don't drink the water. They put something in it to make you forget. I don't even remember how I got here.", "vo/trainyard/cit_water.wav")
Schema.voices.Add("CitizenMale", "THOUGHT YOU WERE A COP", "Oh, I thought you were a cop.", "vo/trainyard/cit_window_cop.wav")
Schema.voices.Add("CitizenMale", "HOPE YOURE WRONG", "Just this once I hope you're wrong.", "vo/trainyard/cit_window_hope.wav")
Schema.voices.Add("CitizenMale", "LOOK AT THEM", "Look at them down there.", "vo/trainyard/cit_window_look.wav")
Schema.voices.Add("CitizenMale", "ITS ALRIGHT", "It's alright.", "vo/trainyard/husb_allright.wav")
Schema.voices.Add("CitizenMale", "DON'T WORRY", "Don't worry.", "vo/trainyard/husb_dontworry.wav")
Schema.voices.Add("CitizenMale", "GONNA BE OK", "Everything is gonna be ok.", "vo/trainyard/husb_okay.wav")
Schema.voices.Add("CitizenMale", "THINK OF SOMETHING", "We'll think of something.", "vo/trainyard/husb_think.wav")
Schema.voices.Add("CitizenMale", "ME", "Me?!", "vo/trainyard/man_me.wav")
Schema.voices.Add("CitizenMale", "WAIT A MINUTE", "Wait a minute.", "vo/trainyard/man_waitaminute.wav")
Schema.voices.Add("CitizenMale", "TAKING ME", "Where are you taking me?", "vo/trainyard/man_whereyoutakingme.wav")
Schema.voices.Add("CitizenMale", "STAY BACK", "Stay back, you'll sttract unwanted attention", "vo/trainyard/male01/cit_bench01.wav")
Schema.voices.Add("CitizenMale", "CAN'T BE SEEN", "I can't be seen talking to you, not out here.", "vo/trainyard/male01/cit_bench02.wav")
Schema.voices.Add("CitizenMale", "DON'T SIT", "Don't sit near me, it'll look suspicious.", "vo/trainyard/male01/cit_bench03.wav")
Schema.voices.Add("CitizenMale", "PIGEONS", "You're scaring off the pigeons.", "vo/trainyard/male01/cit_bench04.wav")
Schema.voices.Add("CitizenMale", "LINE", "The line starts at the end.", "vo/trainyard/male01/cit_foodline01.wav")
Schema.voices.Add("CitizenMale", "WAIT YOUR TURN", "You'll have to wait your turn like everybody else.", "vo/trainyard/male01/cit_foodline02.wav")
Schema.voices.Add("CitizenMale", "DAMN HUNGRY", "You gotta be damn hungry to wait in line for this crap.", "vo/trainyard/male01/cit_foodline03.wav")
Schema.voices.Add("CitizenMale", "JOIN CP", "I don't know about you, but I'm ready to join Civil Protection just to get a decent meal.", "vo/trainyard/male01/cit_foodline04.wav")
Schema.voices.Add("CitizenMale", "CUT IT OUT", "Cut it out!", "vo/trainyard/male01/cit_hit01.wav")
Schema.voices.Add("CitizenMale", "STOP THAT", "Stop that!", "vo/trainyard/male01/cit_hit02.wav")
Schema.voices.Add("CitizenMale", "WATCH IT", "Watch it will you?", "vo/trainyard/male01/cit_hit03.wav")
Schema.voices.Add("CitizenMale", "NO MORE", "No more.", "vo/trainyard/male01/cit_hit04.wav")
Schema.voices.Add("CitizenMale", "ENOUGH OF THAT", "That's enough of that!", "vo/trainyard/male01/cit_hit05.wav")
Schema.voices.Add("CitizenMale", "NEW IN TOWN", "New in town, aren't you?", "vo/trainyard/male01/cit_pedestrian01.wav")
Schema.voices.Add("CitizenMale", "KEEP IT TO YOU", "Word to the wise, keep it to youself.", "vo/trainyard/male01/cit_pedestrian02.wav")
Schema.voices.Add("CitizenMale", "BOTH BE IN TROUBLE", "If I talk to you out here, we'll both be in trouble.", "vo/trainyard/male01/cit_pedestrian03.wav")
Schema.voices.Add("CitizenMale", "CAN'T BESEEN2", "We can't be seen talking to each other.", "vo/trainyard/male01/cit_pedestrian04.wav")
Schema.voices.Add("CitizenMale", "LIKE TO HELP YOU", "I'd like to help you, but it's out of the question.", "vo/trainyard/male01/cit_pedestrian05.wav")
Schema.voices.Add("CitizenMale", "THIRD TRANSFER", "This is my third transfer this year.", "vo/trainyard/male01/cit_term_ques02.wav")
Schema.voices.Add("CitizenMale", "REALLY GONNA GET IT", "Oh no. Now we're really gonna get it.", "vo/trainyard/male01/cit_tvbust05.wav")
Schema.voices.Add("CitizenMale", "DOESNT LOOK GOOD", "This doesn't look good.", "vo/trainyard/male01/cit_window_use01.wav")
Schema.voices.Add("CitizenMale", "COMING IN HERE", "They're definitely coming in here.", "vo/trainyard/male01/cit_window_use02.wav")
Schema.voices.Add("CitizenMale", "MATTER OF TIME", "It was just a matter of time.", "vo/trainyard/male01/cit_window_use03.wav")
Schema.voices.Add("CitizenMale", "NEIGHBORHOOD", "Here goes the rest of the neighborhood.", "vo/trainyard/male01/cit_window_use04.wav")
Schema.voices.Add("CitizenMale", "CRY1", "*Cries*", "ambient/creatures/town_scared_breathing1.wav")
Schema.voices.Add("CitizenMale", "CRY2", "*Cries*", "ambient/creatures/town_scared_breathing2.wav")
Schema.voices.Add("CitizenMale", "COUGH1", "*Coughs*", "ambient/voices/cough1.wav")
Schema.voices.Add("CitizenMale", "COUGH2", "*Coughs*", "ambient/voices/cough2.wav")
Schema.voices.Add("CitizenMale", "COUGH3", "*Coughs*", "ambient/voices/cough3.wav")
Schema.voices.Add("CitizenMale", "COUGH4", "*Coughs*", "ambient/voices/cough4.wav")

Schema.voices.Add("CitizenFemale", "ONLY ONES", "Were you the only ones on that train?", "vo/trainyard/cit_fence_onlyones.wav")
Schema.voices.Add("CitizenFemale", "ONE OF US", "He's one of us.", "vo/trainyard/cit_window_stand.wav")
Schema.voices.Add("CitizenFemale", "COMING FOR US NEXT", "I told you they'd be coming for us next.", "vo/trainyard/cit_window_usnext.wav")
Schema.voices.Add("CitizenFemale", "CAN'T TAKE IT", "I can't take it anymore.", "vo/trainyard/wife_canttake.wav")
Schema.voices.Add("CitizenFemale", "ALLGOINGTOEND", "When is it all going to end?", "vo/trainyard/wife_end.wav")
Schema.voices.Add("CitizenFemale", "PLEASE", "Please.", "vo/trainyard/wife_please.wav")
Schema.voices.Add("CitizenFemale", "GOING TO DO", "What are we going to do?", "vo/trainyard/wife_whattodo.wav")
Schema.voices.Add("CitizenFemale", "STAY BACK", "Stay back, you;ll sttract unwanted attention", "vo/trainyard/female01/cit_bench01.wav")
Schema.voices.Add("CitizenFemale", "CAN'T BE SEEN", "I can't be seen talking to you, not out here.", "vo/trainyard/female01/cit_bench02.wav")
Schema.voices.Add("CitizenFemale", "DON'T SIT", "Don't sit near me, it'll look suspicious.", "vo/trainyard/female01/cit_bench03.wav")
Schema.voices.Add("CitizenFemale", "PIGEONS", "You're scaring off the pigeons.", "vo/trainyard/female01/cit_bench04.wav")
Schema.voices.Add("CitizenFemale", "LINE", "The line starts at the end.", "vo/trainyard/female01/cit_foodline01.wav")
Schema.voices.Add("CitizenFemale", "WAIT YOUR TURN", "You'll have to wait your turn like everybody else.", "vo/trainyard/female01/cit_foodline02.wav")
Schema.voices.Add("CitizenFemale", "DAMN HUNGRY", "You gotta be damn hungry to wait in line for this crap.", "vo/trainyard/female01/cit_foodline03.wav")
Schema.voices.Add("CitizenFemale", "JOIN CP", "I don't know about you, but I'm ready to join Civil Protection just to get a decent meal.", "vo/trainyard/female01/cit_foodline04.wav")
Schema.voices.Add("CitizenFemale", "CUT IT OUT", "Cut it out!", "vo/trainyard/female01/cit_hit01.wav")
Schema.voices.Add("CitizenFemale", "STOP THAT", "Stop that!", "vo/trainyard/female01/cit_hit02.wav")
Schema.voices.Add("CitizenFemale", "WATCH IT WILL YOU", "Watch it will you?", "vo/trainyard/female01/cit_hit03.wav")
Schema.voices.Add("CitizenFemale", "NO MORE", "No more.", "vo/trainyard/female01/cit_hit04.wav")
Schema.voices.Add("CitizenFemale", "ENOUGH OF THAT", "That's enough of that!", "vo/trainyard/female01/cit_hit05.wav")
Schema.voices.Add("CitizenFemale", "NEW IN TOWN", "New in town, aren't you?", "vo/trainyard/female01/cit_pedestrian01.wav")
Schema.voices.Add("CitizenFemale", "KEEP IT TO YOU", "Word to the wise, keep it to youself.", "vo/trainyard/female01/cit_pedestrian02.wav")
Schema.voices.Add("CitizenFemale", "BOTH BE IN TROUBLE", "If I talk to you out here, we'll both be in trouble.", "vo/trainyard/female01/cit_pedestrian03.wav")
Schema.voices.Add("CitizenFemale", "CAN'T BE SEEN2", "We can't be seen talking to each other.", "vo/trainyard/female01/cit_pedestrian04.wav")
Schema.voices.Add("CitizenFemale", "LIKE TO HELP YOU", "I'd like to help you, but it's out of the question.", "vo/trainyard/female01/cit_pedestrian05.wav")
Schema.voices.Add("CitizenFemale", "SOMEONE HAD COURAGE", "Thank God someone had the courage to do that.", "vo/trainyard/female01/cit_tvbust05.wav")
Schema.voices.Add("CitizenFemale", "DOESNT LOOK GOOD", "This doesn't look good.", "vo/trainyard/female01/cit_window_use01.wav")
Schema.voices.Add("CitizenFemale", "COMING IN HERE", "They're definitely coming in here.", "vo/trainyard/female01/cit_window_use02.wav")
Schema.voices.Add("CitizenFemale", "MATTER OF TIME", "It was just a matter of time.", "vo/trainyard/female01/cit_window_use03.wav")
Schema.voices.Add("CitizenFemale", "NEIGHBORHOOD", "Here goes the rest of the neighborhood.", "vo/trainyard/female01/cit_window_use04.wav")
Schema.voices.Add("CitizenFemale", "CRY1", "*Cries*", "ambient/creatures/town_scared_breathing1.wav")
Schema.voices.Add("CitizenFemale", "CRY2", "*Cries*", "ambient/creatures/town_scared_breathing2.wav")
Schema.voices.Add("CitizenFemale", "COUGH1", "*Coughs*", "ambient/voices/cough1.wav")
Schema.voices.Add("CitizenFemale", "COUGH2", "*Coughs*", "ambient/voices/cough2.wav")
Schema.voices.Add("CitizenFemale", "COUGH3", "*Coughs*", "ambient/voices/cough3.wav")
Schema.voices.Add("CitizenFemale", "COUGH4", "*Coughs*", "ambient/voices/cough4.wav")


Schema.voices.AddClass("CitizenMale", function(ply)
	local factionTable = ix.faction.Get(ply:Team())
	if ( ( ply:IsCitizen() ) and not ply:IsFemale() ) then
		return true
	end
end)

Schema.voices.AddClass("CitizenFemale", function(ply)
	local factionTable = ix.faction.Get(ply:Team())
	if ( ( ply:IsCitizen() ) and ply:IsFemale() ) then
		return true
	end
end)